<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cybersecurity Audit Report</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f4f7f9;
            color: #333;
            padding: 20px;
        }
        .container {
            background: white;
            max-width: 800px;
            margin: 0 auto;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 0 15px rgba(0,0,0,0.1);
        }
        h1 {
            color: #0077cc;
            margin-bottom: 10px;
        }
        .score, .level {
            font-weight: bold;
            font-size: 1.2em;
            margin-bottom: 15px;
        }
        .question {
            margin-bottom: 25px;
        }
        .question h3 {
            color: #222;
        }
        .question p {
            margin: 4px 0;
        }
        .footer {
            margin-top: 40px;
            font-size: 0.9em;
            color: #777;
            text-align: center;
        }
        .highlight {
            background: #ffe8e8;
            padding: 10px;
            border-left: 4px solid #d40000;
            border-radius: 6px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Cybersecurity Assessment Results</h1>
        <div class="score">Your score: {{ score }} out of {{ total }}</div>
        <div class="level">Risk Level: {{ level }}</div>

        {% if failed_questions %}
            <h2>Areas for Improvement:</h2>
            {% for item in failed_questions %}
                <div class="question highlight">
                    <h3>{{ item.question }}</h3>
                    <p><strong>Why it matters:</strong> {{ item.explanation }}</p>
                    <p><strong>How attackers exploit it:</strong> {{ item.exploitation }}</p>
                    <p><strong>Impact on clients:</strong> {{ item.client_impact }}</p>
                    <p><strong>Compliance:</strong> {{ item.compliance.replace('HIPAA/Compliance:', '').strip() }}</p>
                    <p><strong>How I can help:</strong> {{ item.help }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>Excellent work! Your cybersecurity posture is strong across all checkpoints.</p>
        {% endif %}

        <div class="footer">
            This report was generated by Harold L.R. Watkins — Cybersecurity Specialist in Automotive Tech.<br>
            Built with Flask, Render, and a mission to protect small to mid-sized auto shops.
        </div>
    </div>
</body>
</html>
